Specify OpenSSL specific versions supported
Because it fails to compile with OpenSSL 1.0:

> nginx-cloudflare-jwt-checker-0/src/ngx_http_jwt_cf_jwk_decode.c:85:5: error: implicit declaration of function 'RSA_set0_key'; did you mean 'RSA_check_key'